import { StockSearchResult } from './stocks.types';

export const STOCKS_CATALOG: StockSearchResult[] = [
  // ─── Bancos ───────────────────────────────────────────────────────────────
  { ticker: 'BBAS3',  nome: 'Banco do Brasil ON',     setor: 'Bancos' },
  { ticker: 'BBDC3',  nome: 'Bradesco ON',            setor: 'Bancos' },
  { ticker: 'BBDC4',  nome: 'Bradesco PN',            setor: 'Bancos' },
  { ticker: 'ITUB3',  nome: 'Itaú Unibanco ON',       setor: 'Bancos' },
  { ticker: 'ITUB4',  nome: 'Itaú Unibanco PN',       setor: 'Bancos' },
  { ticker: 'ITSA3',  nome: 'Itaúsa ON',              setor: 'Bancos' },
  { ticker: 'ITSA4',  nome: 'Itaúsa PN',              setor: 'Bancos' },
  { ticker: 'SANB11', nome: 'Santander Brasil UNT',   setor: 'Bancos' },
  { ticker: 'BPAC11', nome: 'BTG Pactual UNT',        setor: 'Bancos' },
  { ticker: 'BRSR6',  nome: 'Banrisul PN',            setor: 'Bancos' },
  { ticker: 'BMGB4',  nome: 'Banco BMG PN',           setor: 'Bancos' },
  { ticker: 'PINE4',  nome: 'Banco Pine PN',          setor: 'Bancos' },
  { ticker: 'ABCB4',  nome: 'ABC Brasil PN',          setor: 'Bancos' },
  // ─── Seguros ──────────────────────────────────────────────────────────────
  { ticker: 'BBSE3',  nome: 'BB Seguridade ON',           setor: 'Seguros' },
  { ticker: 'CXSE3',  nome: 'Caixa Seguridade ON',        setor: 'Seguros' },
  { ticker: 'IRBR3',  nome: 'IRB Brasil Resseguros ON',   setor: 'Seguros' },
  { ticker: 'PSSA3',  nome: 'Porto Seguro ON',            setor: 'Seguros' },
  // ─── Serviços Financeiros ─────────────────────────────────────────────────
  { ticker: 'B3SA3',  nome: 'B3 S.A. ON',            setor: 'Serviços Financeiros' },
  { ticker: 'TOTS3',  nome: 'Totvs ON',              setor: 'Serviços Financeiros' },
  // ─── Petróleo e Gás ───────────────────────────────────────────────────────
  { ticker: 'PETR3',  nome: 'Petrobras ON',          setor: 'Petróleo e Gás' },
  { ticker: 'PETR4',  nome: 'Petrobras PN',          setor: 'Petróleo e Gás' },
  { ticker: 'PRIO3',  nome: 'PetroRio ON',           setor: 'Petróleo e Gás' },
  { ticker: 'RECV3',  nome: 'Recôncavo ON',          setor: 'Petróleo e Gás' },
  { ticker: 'BRAV3',  nome: 'Brava Energia ON',      setor: 'Petróleo e Gás' },
  { ticker: 'RAIZ4',  nome: 'Raízen PN',             setor: 'Petróleo e Gás' },
  { ticker: 'CSAN3',  nome: 'Cosan ON',              setor: 'Petróleo e Gás' },
  { ticker: 'UGPA3',  nome: 'Ultrapar ON',           setor: 'Petróleo e Gás' },
  { ticker: 'VBBR3',  nome: 'Vibra Energia ON',      setor: 'Petróleo e Gás' },
  // ─── Petroquímica ─────────────────────────────────────────────────────────
  { ticker: 'BRKM3',  nome: 'Braskem ON',            setor: 'Petroquímica' },
  { ticker: 'BRKM5',  nome: 'Braskem PNA',           setor: 'Petroquímica' },
  // ─── Energia Elétrica ─────────────────────────────────────────────────────
  { ticker: 'ALUP11', nome: 'Alupar UNT',            setor: 'Energia Elétrica' },
  { ticker: 'AURE3',  nome: 'Auren Energia ON',      setor: 'Energia Elétrica' },
  { ticker: 'CMIG3',  nome: 'Cemig ON',              setor: 'Energia Elétrica' },
  { ticker: 'CMIG4',  nome: 'Cemig PN',              setor: 'Energia Elétrica' },
  { ticker: 'CPLE3',  nome: 'Copel ON',              setor: 'Energia Elétrica' },
  { ticker: 'CPFE3',  nome: 'CPFL Energia ON',       setor: 'Energia Elétrica' },
  { ticker: 'EGIE3',  nome: 'Engie Brasil ON',       setor: 'Energia Elétrica' },
  { ticker: 'ENEV3',  nome: 'Eneva ON',              setor: 'Energia Elétrica' },
  { ticker: 'ENGI11', nome: 'Energisa UNT',          setor: 'Energia Elétrica' },
  { ticker: 'EQTL3',  nome: 'Equatorial Energia ON', setor: 'Energia Elétrica' },
  { ticker: 'ISAE4',  nome: 'ISA Cteep PN',          setor: 'Energia Elétrica' },
  { ticker: 'NEOE3',  nome: 'Neoenergia ON',         setor: 'Energia Elétrica' },
  { ticker: 'TAEE11', nome: 'Taesa UNT',             setor: 'Energia Elétrica' },
  // ─── Saneamento ───────────────────────────────────────────────────────────
  { ticker: 'AMBP3',  nome: 'Ambipar ON',   setor: 'Saneamento' },
  { ticker: 'CSMG3',  nome: 'Copasa ON',    setor: 'Saneamento' },
  { ticker: 'SAPR11', nome: 'Sanepar UNT',  setor: 'Saneamento' },
  { ticker: 'SBSP3',  nome: 'Sabesp ON',    setor: 'Saneamento' },
  // ─── Papel e Celulose ─────────────────────────────────────────────────────
  { ticker: 'DXCO3',  nome: 'Dexco ON',    setor: 'Papel e Celulose' },
  { ticker: 'KLBN11', nome: 'Klabin UNT',  setor: 'Papel e Celulose' },
  { ticker: 'RANI3',  nome: 'Irani Papel ON', setor: 'Papel e Celulose' },
  { ticker: 'SUZB3',  nome: 'Suzano ON',   setor: 'Papel e Celulose' },
  // ─── Telecomunicações ─────────────────────────────────────────────────────
  { ticker: 'TIMS3',  nome: 'TIM ON',              setor: 'Telecomunicações' },
  { ticker: 'VIVT3',  nome: 'Telefônica Vivo ON',  setor: 'Telecomunicações' },
  // ─── Saúde ────────────────────────────────────────────────────────────────
  { ticker: 'FLRY3',  nome: 'Fleury ON',                        setor: 'Saúde' },
  { ticker: 'HAPV3',  nome: 'Hapvida ON',                       setor: 'Saúde' },
  { ticker: 'HYPE3',  nome: 'Hypera Pharma ON',                 setor: 'Saúde' },
  { ticker: 'MATD3',  nome: 'Mater Dei ON',                     setor: 'Saúde' },
  { ticker: 'ODPV3',  nome: 'Odontoprev ON',                    setor: 'Saúde' },
  { ticker: 'PGMN3',  nome: 'Pague Menos ON',                   setor: 'Saúde' },
  { ticker: 'QUAL3',  nome: 'Qualicorp ON',                     setor: 'Saúde' },
  { ticker: 'RADL3',  nome: 'Raia Drogasil ON',                 setor: 'Saúde' },
  { ticker: 'RDOR3',  nome: "Rede D'Or ON",                     setor: 'Saúde' },
  // ─── Varejo ───────────────────────────────────────────────────────────────
  { ticker: 'AMER3',  nome: 'Americanas ON',          setor: 'Varejo' },
  { ticker: 'ASAI3',  nome: 'Assaí Atacadista ON',    setor: 'Varejo' },
  { ticker: 'CEAB3',  nome: 'C&A Modas ON',           setor: 'Varejo' },
  { ticker: 'GMAT3',  nome: 'Grupo Mateus ON',        setor: 'Varejo' },
  { ticker: 'GRND3',  nome: 'Grendene ON',            setor: 'Varejo' },
  { ticker: 'LREN3',  nome: 'Lojas Renner ON',        setor: 'Varejo' },
  { ticker: 'MGLU3',  nome: 'Magazine Luiza ON',      setor: 'Varejo' },
  { ticker: 'PCAR3',  nome: 'Grupo Pão de Açúcar ON', setor: 'Varejo' },
  { ticker: 'SMFT3',  nome: 'Smart Fit ON',           setor: 'Varejo' },
  { ticker: 'VIVA3',  nome: 'Vivara ON',              setor: 'Varejo' },
  { ticker: 'VULC3',  nome: 'Vulcabras ON',           setor: 'Varejo' },
  // ─── Mineração ────────────────────────────────────────────────────────────
  { ticker: 'BRAP4',  nome: 'Bradespar PN',      setor: 'Mineração' },
  { ticker: 'CBAV3',  nome: 'CBA ON',            setor: 'Mineração' },
  { ticker: 'CMIN3',  nome: 'CSN Mineração ON',  setor: 'Mineração' },
  { ticker: 'VALE3',  nome: 'Vale ON',           setor: 'Mineração' },
  // ─── Siderurgia ───────────────────────────────────────────────────────────
  { ticker: 'CSNA3',  nome: 'CSN ON',                setor: 'Siderurgia' },
  { ticker: 'FESA4',  nome: 'Ferbasa PN',            setor: 'Siderurgia' },
  { ticker: 'GGBR3',  nome: 'Gerdau ON',             setor: 'Siderurgia' },
  { ticker: 'GGBR4',  nome: 'Gerdau PN',             setor: 'Siderurgia' },
  { ticker: 'GOAU4',  nome: 'Metalúrgica Gerdau PN', setor: 'Siderurgia' },
  { ticker: 'USIM3',  nome: 'Usiminas ON',           setor: 'Siderurgia' },
  { ticker: 'USIM5',  nome: 'Usiminas PNA',          setor: 'Siderurgia' },
  // ─── Construção Civil ─────────────────────────────────────────────────────
  { ticker: 'CURY3',  nome: 'Cury Construtora ON',       setor: 'Construção Civil' },
  { ticker: 'CYRE3',  nome: 'Cyrela Realty ON',          setor: 'Construção Civil' },
  { ticker: 'DIRR3',  nome: 'Direcional ON',             setor: 'Construção Civil' },
  { ticker: 'EVEN3',  nome: 'Even Construtora ON',       setor: 'Construção Civil' },
  { ticker: 'EZTC3',  nome: 'EZTEC ON',                  setor: 'Construção Civil' },
  { ticker: 'HBOR3',  nome: 'Helbor ON',                 setor: 'Construção Civil' },
  { ticker: 'JHSF3',  nome: 'JHSF Participações ON',     setor: 'Construção Civil' },
  { ticker: 'LAVV3',  nome: 'Lavvi Incorporadora ON',     setor: 'Construção Civil' },
  { ticker: 'MELK3',  nome: 'Melnick ON',                setor: 'Construção Civil' },
  { ticker: 'MRVE3',  nome: 'MRV Engenharia ON',         setor: 'Construção Civil' },
  { ticker: 'PLPL3',  nome: 'Plano & Plano ON',          setor: 'Construção Civil' },
  { ticker: 'TEND3',  nome: 'Construtora Tenda ON',      setor: 'Construção Civil' },
  { ticker: 'TRIS3',  nome: 'Trisul ON',                 setor: 'Construção Civil' },
  // ─── Shoppings e Imóveis Comerciais ───────────────────────────────────────
  { ticker: 'IGTI3',  nome: 'Iguatemi ON',   setor: 'Shoppings' },
  { ticker: 'IGTI11', nome: 'Iguatemi UNT',  setor: 'Shoppings' },
  { ticker: 'MULT3',  nome: 'Multiplan ON',  setor: 'Shoppings' },
  // ─── Logística e Transporte ───────────────────────────────────────────────
  { ticker: 'ECOR3',  nome: 'EcoRodovias ON',               setor: 'Logística' },
  { ticker: 'JSLG3',  nome: 'JSL Logística ON',             setor: 'Logística' },
  { ticker: 'LOGG3',  nome: 'Log Commercial Properties ON', setor: 'Logística' },
  { ticker: 'MILS3',  nome: 'Mills Locações ON',            setor: 'Logística' },
  { ticker: 'RAIL3',  nome: 'Rumo Logística ON',            setor: 'Logística' },
  { ticker: 'SIMH3',  nome: 'Simpar ON',                    setor: 'Logística' },
  { ticker: 'TGMA3',  nome: 'Tegma Gestão Logística ON',   setor: 'Logística' },
  { ticker: 'VAMO3',  nome: 'Vamos Locação ON',             setor: 'Logística' },
  // ─── Veículos e Peças ─────────────────────────────────────────────────────
  { ticker: 'FRAS3',  nome: 'Fras-le ON',        setor: 'Veículos e Peças' },
  { ticker: 'LEVE3',  nome: 'Metal Leve ON',     setor: 'Veículos e Peças' },
  { ticker: 'MYPK3',  nome: 'Iochpe-Maxion ON',  setor: 'Veículos e Peças' },
  { ticker: 'POMO3',  nome: 'Marcopolo ON',      setor: 'Veículos e Peças' },
  { ticker: 'POMO4',  nome: 'Marcopolo PN',      setor: 'Veículos e Peças' },
  { ticker: 'RAPT3',  nome: 'Randon ON',         setor: 'Veículos e Peças' },
  { ticker: 'RAPT4',  nome: 'Randon PN',         setor: 'Veículos e Peças' },
  { ticker: 'TUPY3',  nome: 'Tupy ON',           setor: 'Veículos e Peças' },
  // ─── Locação de Veículos ──────────────────────────────────────────────────
  { ticker: 'MOVI3',  nome: 'Movida ON',    setor: 'Locação de Veículos' },
  { ticker: 'RENT3',  nome: 'Localiza ON',  setor: 'Locação de Veículos' },
  // ─── Agronegócio ──────────────────────────────────────────────────────────
  { ticker: 'AGRO3',  nome: 'BrasilAgro ON',        setor: 'Agronegócio' },
  { ticker: 'CAML3',  nome: 'Camil Alimentos ON',   setor: 'Agronegócio' },
  { ticker: 'SLCE3',  nome: 'SLC Agrícola ON',      setor: 'Agronegócio' },
  { ticker: 'SMTO3',  nome: 'São Martinho ON',      setor: 'Agronegócio' },
  { ticker: 'SOJA3',  nome: 'Boa Safra Sementes ON', setor: 'Agronegócio' },
  // ─── Alimentos e Bebidas ──────────────────────────────────────────────────
  { ticker: 'ABEV3',  nome: 'Ambev ON',         setor: 'Alimentos e Bebidas' },
  { ticker: 'BEEF3',  nome: 'Minerva Foods ON', setor: 'Alimentos e Bebidas' },
  { ticker: 'MDIA3',  nome: 'M. Dias Branco ON', setor: 'Alimentos e Bebidas' },
  // ─── Tecnologia ───────────────────────────────────────────────────────────
  { ticker: 'BMOB3',  nome: 'Bemobi Mobile Tech ON',  setor: 'Tecnologia' },
  { ticker: 'CASH3',  nome: 'Méliuz ON',              setor: 'Tecnologia' },
  { ticker: 'INTB3',  nome: 'Intelbras ON',           setor: 'Tecnologia' },
  { ticker: 'LWSA3',  nome: 'Locaweb ON',             setor: 'Tecnologia' },
  { ticker: 'POSI3',  nome: 'Positivo Tecnologia ON', setor: 'Tecnologia' },
  // ─── Bens Industriais ─────────────────────────────────────────────────────
  { ticker: 'ETER3',  nome: 'Eternit ON',    setor: 'Bens Industriais' },
  { ticker: 'KEPL3',  nome: 'Kepler Weber ON', setor: 'Bens Industriais' },
  { ticker: 'ROMI3',  nome: 'Romi ON',       setor: 'Bens Industriais' },
  { ticker: 'SHUL4',  nome: 'Schulz PN',     setor: 'Bens Industriais' },
  { ticker: 'WEGE3',  nome: 'WEG ON',        setor: 'Bens Industriais' },
  // ─── Educação ─────────────────────────────────────────────────────────────
  { ticker: 'ANIM3',  nome: 'Ânima Educação ON',                setor: 'Educação' },
  { ticker: 'COGN3',  nome: 'Cogna Educação ON',                setor: 'Educação' },
  { ticker: 'YDUQ3',  nome: 'Yduqs Participações ON',           setor: 'Educação' },
  // ─── Têxtil ───────────────────────────────────────────────────────────────
  { ticker: 'CAMB3',  nome: 'Cambuci ON',    setor: 'Têxtil' },
  { ticker: 'CTKA3',  nome: 'Karsten ON',    setor: 'Têxtil' },
  // ─── Imobiliário ──────────────────────────────────────────────────────────
  { ticker: 'LPSB3',  nome: 'LPS Brasil ON',              setor: 'Imobiliário' },
  { ticker: 'SCAR3',  nome: 'São Carlos Emp. e Part. ON', setor: 'Imobiliário' },
  // ─── Calçados ─────────────────────────────────────────────────────────────
  { ticker: 'ALPA4',  nome: 'Alpargatas PN',  setor: 'Calçados' },
  // ─── Defesa ───────────────────────────────────────────────────────────────
  { ticker: 'TASA3',  nome: 'Taurus Armas ON',  setor: 'Defesa' },
  { ticker: 'TASA4',  nome: 'Taurus Armas PN',  setor: 'Defesa' },
];
